apiVersion: apps/v1
kind: Deployment

metadata:
  name: boston-house-price-api

spec:

  replicas: 1

  selector:
    matchLabels:
      app: boston-house-price-api

  template:

    metadata:
      labels:
        app: boston-house-price-api

    spec:

      containers:

        - name: boston-house-price-api

          image: boston-house-price-api:1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 20
            periodSeconds: 20
