apiVersion: v1
kind: Service

metadata:
  name: boston-house-price-service

spec:

  type: NodePort

  selector:
    app: boston-house-price-api

  ports:

    - protocol: TCP

      port: 8000

      targetPort: 8000

      nodePort: 30081
